# Generated by Django 5.2.7 on 2025-10-19 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان منبع")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نویسنده / پدیدآور"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("book", "کتاب"),
                            ("article", "مقاله"),
                            ("website", "وب\u200cسایت"),
                            ("other", "سایر"),
                        ],
                        default="book",
                        max_length=20,
                        verbose_name="نوع منبع",
                    ),
                ),
                (
                    "publish_year",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="سال انتشار"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان فیش")),
                ("content", models.TextField(verbose_name="متن فیش")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("quote", "نقل قول"),
                            ("summary", "خلاصه"),
                            ("idea", "یادداشت شخصی"),
                        ],
                        default="summary",
                        max_length=20,
                        verbose_name="نوع فیش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس"), ("final", "نهایی")],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کلیدواژه"
                    ),
                ),
                (
                    "notes",
                    models.ManyToManyField(
                        blank=True, related_name="keywords", to="research.researchnote"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان پروژه")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات پروژه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدیر پروژه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=50, verbose_name="نقش (مثلاً پژوهشگر، ویراستار،...)"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="research.researchproject",
                        verbose_name="پروژه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان موضوع")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="research.researchproject",
                        verbose_name="پروژه",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="researchnote",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="research.researchtopic",
                verbose_name="موضوع",
            ),
        ),
        migrations.AddField(
            model_name="researchnote",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.source",
                verbose_name="منبع",
            ),
        ),
    ]
